schema_version: 1

context:
  version: 0.2.0

package:
  name: cmac
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cmac/cmac-${{ version }}.tar.gz
  sha256: b7339669ef5a9e21a28005ca297b05857cc95fa9730c751b5b2ff8aef084ba3c

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - numpy >=2
    - setuptools >=77
    - wheel
    - cython
    - pip
    - xarray
    - arm_pyart
    - scikit-fuzzy
    - wradlib
    - s3fs >=2021.11.0
  run:
    - python
    - scipy
    - matplotlib-base
    - pyyaml
    - cartopy
    - cmweather
    - netcdf4
    - distributed
    - xarray
    - arm_pyart
    - scikit-fuzzy
    - wradlib
    - s3fs >=2021.11.0

tests:
  - python:
      imports:
        - cmac
    script:
      - pip check

about:
  summary: Corrected Moments in Antenna Coordinates
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - LICENSE_GPL.txt
  homepage: https://github.com/ARM-Development/cmac

extra:
  recipe-maintainers:
    - rcjackson
    - zssherman
